version: '3.9'

services:
  database:
    image: postgres:13
    container_name: database
    build:
      context: ./database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: corporate_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - app_network

  backend:
    container_name: backend
    build:
      context: ./app/backend
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=corporate_db
      - DB_USER=admin
      - DB_PASSWORD=password
    ports:
      - "5000:5000"
    networks:
      - app_network
    depends_on:
      - database

  auth:
    container_name: auth
    build:
      context: ./app/auth
    ports:
      - "5001:5001"
    networks:
      - app_network

  logs:
    container_name: logs
    build:
      context: ./app/logs
    ports:
      - "5002:5002"
    volumes:
      - ./logs_data:/app/logs  # Привязываем папку на хосте
    networks:
      - app_network


  frontend:
    container_name: frontend
    build:
      context: ./app/frontend
    ports:
      - "5003:5003"
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - app_network
    depends_on:
      - frontend
      - auth
      - backend


volumes:
  db_data:

networks:
  app_network:
